services:
  docs:
    image: narvi_task_local_docs
    container_name: narvi_task_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./narvi_task:/app/narvi_task:z
    ports:
      - '9000:9000'
    command: /start-docs
